eureka: 
  instance: 
    hostname: center #服务注册中心IP地址
  client: 
    fetch-registry: true
    register-with-eureka: true
    serviceUrl: 
      #注册地址为集群.
      #defaultZone: http://node1:1111/eureka/,http://node3:3333/eureka/,http://node2:2222/eureka/
      defaultZone: http://47.105.104.105:10000/eureka/
      
server:
  port: 10001
  
spring:
  application:
    name: zuul
  
  
zuul:
  routes:
    good:
      path: /good/**
      url: good  
    user: 
      path: /user/**
      url: user-service
    pay:
      path: /pay/**
      url: pay-service